# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rspec-webservice-outputter 0.4.3 ruby lib

Gem::Specification.new do |s|
  s.name = "rspec-webservice-outputter"
  s.version = "0.4.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Nicholas Babb"]
  s.date = "2018-04-26"
  s.email = "ndbabb@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rubocop.yml",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/rspec-webservice-outputter.rb",
    "lib/rspec-webservice-outputter/base.rb",
    "rspec-webservice-outputter.gemspec",
    "spec/output_spec.rb",
    "spec/request_spec.rb",
    "spec/response_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/ndbabb/rspec-webservice-outputter"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5.2"
  s.summary = "Outputs webservice request/response JSON data for rails rspec request specs"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rspec>, [">= 3.4"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<juwelier>, ["~> 2.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0.11"])
      s.add_development_dependency(%q<rubocop>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 3.4"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<juwelier>, ["~> 2.4"])
      s.add_dependency(%q<simplecov>, [">= 0.11"])
      s.add_dependency(%q<rubocop>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 3.4"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<juwelier>, ["~> 2.4"])
    s.add_dependency(%q<simplecov>, [">= 0.11"])
    s.add_dependency(%q<rubocop>, [">= 0"])
  end
end

